language: go

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

go: 
    - 1.3
    - release
    - tip

script:
    - make test
    - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_REPO_TOKEN
